### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by redfieldp** [rpi-ws281x/rpi-ws281x-java#10]
I successfully generated the source and the .so using the scripts provided, but is there any chance of providing some examples? It would be great to see the intended use of the API.

**Comment by redfieldp** [comment]
I circumvented this by using the Python version and sending messages from Processing via OSC. Nonetheless, it would be nice to see some example code like there is on the Python side of things.

**Comment by PioBeat** [comment]
You can have a look at the comments here https://github.com/rpi-ws281x/rpi-ws281x-java/blob/master/src/main/java/com/github/mbelling/ws281x/Ws281xLedStrip.java
