### ISSUE TITLE
Error with Raspberry Pi 4B

### ISSUE THREAD

**Issue by ianfd** [rpi-ws281x/rpi-ws281x-java#18]
Hey together, I saw that some other of you had the same issue with the raspberry pi 4B and the solutions there don't help me. it's still the error `WS2811_ERROR_HW_NOT_SUPPORTED`. Is there any fix?

I'm using OpenJdk-11 and Micronaut for the rest stuff.

Many thanks for the answers!

**Comment by ianfd** [comment]
Okey, nvm I solved this error on my own by not only changing the checkout part in the `createNativeLib.sh` to `31f668cc637cd96e132b611db82cbe9de9838366 ` like @Gadgetoid described, but also changing `Ws281xLedStrip` into a bean definition.

**Comment by TheHeroGhost** [comment]
> changing `Ws281xLedStrip` into a bean definition.

how did u did this can u help me pls i got the same error?
