### ISSUE TITLE
update gradlew to be able to build on recent java versions

### ISSUE THREAD

**Issue by phips4** [rpi-ws281x/rpi-ws281x-java#21]
With the current version of the wrapper '**gradle-4.5.1**', gradle does not support Java 11+. Therefore, it fails when trying to build making this project unusable for any Java version above 9. (Current LTS version is 11, soon 17) Correct me if I am wrong. 

Gradlew exception:
```
pi@raspberrypi:/tmp/rpi_ws281x_build $ ./gradlew assemble

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.9.1'.
```

For more details: 
https://stackoverflow.com/questions/54358107/gradle-could-not-determine-java-version-from-11-0-2
and
https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by zacaj** [comment]
This fork has an upgraded Gradle, fyi: https://github.com/tom-muir/rpi-ws281x-java
