### ISSUE TITLE
Missing command for publishing to maven local

### ISSUE THREAD

**Issue by Pyro2266** [rpi-ws281x/rpi-ws281x-java#3]
In readme file is mentioned script for publishing jar to local maven repository:
> The easiest way to use the jar would be to publish it to a maven repository, or your local .m2 repository using **./gradlew publishToMavenLocal** and use maven coordinates in your maven or gradle project.

However this command does not work because **publishToMavenLocal** task is not implemented.
It's throwing this error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'publishToMavenLocal' not found in root project 'rpi-ws281x-java'.

**Comment by mbelling** [comment]
I had removed the publishing plugin due to issues for others trying to build.  I will add it back in a simpler form.

**Comment by mbelling** [comment]
Fixed by ea738f8.
