### ISSUE TITLE
Uploading the build artifacts to Maven Central

### ISSUE THREAD

**Issue by sapple-code** [rpi-ws281x/rpi-ws281x-java#8]
Hey, thanks for making this library! 

I've been using it with Clojure with great success. However I was wondering if it is possible to upload the build artifacts from this project to Maven Central?

Forgive my ignorance as I am not that knowledgable about building Java artifacts nor do I understand how wrapping a SWIG interface affects things.

I see there are artifacts for a previous version: https://search.maven.org/artifact/com.github.mbelling/rpi-ws281x-java/1.0.0/pom

Unfortunately that version doesn't expose the same API (Color and LedStrip), though maybe that's due to a difference between building the code locally vs dling the artifacts.

Thanks for your time

**Comment by mbelling** [comment]
Sure, I will see if I can get time to do this in the next week or so.

**Comment by sapple-code** [comment]
Awesome, thanks again for your time.

**Comment by mbelling** [comment]
I changed the version to 2.0.0 since it changed so much, and uploaded the artifacts.  I am not sure what the cycle on getting artifacts to central is, but they should be there eventually. :)

Feel free to close this once you are able to get the artifacts, or I can close in a day or two.

**Comment by mbelling** [comment]
The 2.0.0 artifacts are in maven central now. Closing.
