### ISSUE TITLE
Provide me  a Simple Example with Java

### ISSUE THREAD

**Issue by EduardoAule** [rpi-ws281x/rpi-ws281x-java#9]
Greetings, install this library with some problems in my raspberry pi, for example I had to use:
./gradlew assemble -x signArchives
...
...
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:javadoc UP-TO-DATE
:javadocJar UP-TO-DATE
:sourceJar UP-TO-DATE
:assemble

BUILD SUCCESSFUL in 22s
6 actionable tasks: 6 up-to-date

without the above, it generated an error:
:processResources
:classes
:jar
:javadoc
:javadocJar
:sourceJar
:signArchives FAILED

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':signArchives'.

    Cannot perform signing task ':signArchives' because it has no configured signatory

    Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

    Get more help at https://help.gradle.org

BUILD FAILED in 12m 55s
7 actionable tasks: 7 executed

However someone could provide me with a simple example of how to use it in java. 
thank you.

**Comment by PioBeat** [comment]
Hi,
you can easily include this library in Java by using Maven as a project and build management system.
Within a Maven-based project, you have to create a `pom.xml` file and include the `rpi-ws281x-java` dependency as follows:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>rpi-ws281x-java-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.github.mbelling</groupId>
            <artifactId>rpi-ws281x-java</artifactId>
            <version>2.0.0</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
```

Then, in a newly created Java class, you can instantiate an object of the `Ws281xLedStrip` class, something like this:

```java
import com.github.mbelling.ws281x.Ws281xLedStrip;
// ... 
Ws281xLedStrip strip = new Ws281xLedStrip(4, // led count
                18, // GPIO pin, must support pwm
                800000, //frequency
                10, //DMA, see also https://github.com/jgarff/rpi_ws281x/issues/224
                maxBrightness, //brightness
                0, //pwm channel, GPIO 18 supports PWM0
                false, //invert
                LedStripType.WS2811_STRIP_RGB, 
                true // clear on exit
        );
// switch on LED 0 with RGB values:
int pixelIndex = 0, r = 100, g = 200, b = 100;
strip.setPixel(pixelIndex, r, g, b);
strip.render();
```

I would suggest looking into the comments of that class: https://github.com/rpi-ws281x/rpi-ws281x-java/blob/master/src/main/java/com/github/mbelling/ws281x/Ws281xLedStrip.java to get an idea of what it can provide you with.
